/// Configuration options for a [CiGuard] run.
///
/// In production, instances are built by [OptionsParser.parse] from the CLI
/// arguments. In tests, they can be constructed directly.
class CiGuardOptions {
  /// Default minimum acceptable coverage percentage.
  static const int defaultMinCoverage = 80;

  /// Default file system path to the LCOV report.
  static const String defaultCoveragePath = 'coverage/lcov.info';

  /// Creates a [CiGuardOptions] with all required fields.
  CiGuardOptions({
    required this.minCoverage,
    required this.coveragePath,
    required this.skipFormat,
    required this.skipAnalyze,
    required this.skipTests,
  });

  /// Minimum acceptable coverage percentage (inclusive), in the range `[0, 100]`.
  final int minCoverage;

  /// File system path to the LCOV report generated by `flutter test --coverage`.
  ///
  /// Defaults to `'coverage/lcov.info'` when parsed from the CLI.
  final String coveragePath;

  /// When `true`, the format quality gate is skipped entirely.
  final bool skipFormat;

  /// When `true`, the analyze quality gate is skipped entirely.
  final bool skipAnalyze;

  /// When `true`, the test quality gate is skipped entirely.
  ///
  /// Note: skipping tests does **not** skip the coverage check. The LCOV
  /// file at [coveragePath] must still exist and be valid.
  final bool skipTests;
}
